=== 623162052/java-samples/src/main/java/javase/xml/AttlistID.dtd
<?xml version="1.0" encoding="gb2312"?>

<!ELEMENT Customers	(Customer,Order)>

<!ELEMENT Customer	(Name,Age,Sex)>
<!ELEMENT Name		(#PCDATA)>
<!ELEMENT Age		(#PCDATA)>
<!ELEMENT Sex		(#PCDATA)>
<!ELEMENT Order		(OrderDate,Address)>
<!ELEMENT OrderDate	(#PCDATA)>
<!ELEMENT Address	(#PCDATA)>

<!ATTLIST Customer
	CustomerID		ID		#REQUIRED
>

<!ATTLIST Order
	OrderID			ID		#REQUIRED
	CustomerIDRef	IDREF	#REQUIRED
>

=== 623162052/java-samples/src/main/java/javase/xml/AttlistID.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE Customers SYSTEM "AttlistID.dtd">
<Customers>
	<Customer CustomerID="ACCP001">
		<Name>yufeng</Name>
		<Age>25</Age>
		<Sex>Male</Sex>
	</Customer>
	<Order OrderID="APTECH001" CustomerIDRef="ACCP001">
		<OrderDate>2003-04-05</OrderDate>
		<Address>PKU</Address>
	</Order>
</Customers>
